version: '3.7'

services:
  sintesi-app:
    image: sintesi-app:latest
    container_name: sintesi-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: sintesi.tech
      LETSENCRYPT_HOST: sintesi.tech
      LETSENCRYPT_EMAIL: hello@sintesi.tech
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
    command: >
      sh -c "
      echo 'Creating .env file from environment variables...' &&
      printenv | grep -E '^(OPENAI_API_KEY|ELEVENLABS_API_KEY|DATABASE_URL|AWS_|STRIPE_|RESEND_API_KEY|EMAIL_|LOG_LEVEL|NODE_ENV|TEST_MODE_TOKEN|GOD_MODE_TOKEN)=' > .env &&
      echo '.env file created' &&
      node --env-file=.env index.js
      "
    networks:
      - nginx-proxy
    expose:
      - 3000

networks:
  nginx-proxy:
    external: true
