version: '3'

services:
  app:
    image: ghcr.io/dnlml/sintesi:latest
    expose:
      - '3000'
    environment:
      - VIRTUAL_HOST=sintesi.tech
      - LETSENCRYPT_HOST=sintesi.tech
      - LETSENCRYPT_EMAIL=danielemeli8+sintesi6@gmail.com
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
