version: '3'

services:
  sintesi:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "pnpm install --frozen-lockfile && pnpm build && node ./server/index.js"
    expose:
      - 3000
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
    container_name: sintesi_app
    restart: always
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
