version: '3.7'

services:
  sintesi-app:
    image: sintesi-app:latest
    container_name: sintesi-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: sintesi.tech
      LETSENCRYPT_HOST: sintesi.tech
      LETSENCRYPT_EMAIL: hello@sintesi.tech
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
    networks:
      - nginx-proxy
    expose:
      - 3000

networks:
  nginx-proxy:
    external: true
