name: Deploy SvelteKit to OVH VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build SvelteKit app
        run: pnpm run build

      - name: Copy files to VPS via rsync
        uses: burnett01/rsync-deployments@v2.0.0
        with:
          switches: -avz --delete
          path: ./build/
          remote_path: ~/sites/sintesi/public/
          remote_host: 51.178.44.81
          remote_user: dnlml
          remote_port: 29
          remote_key: ${{ secrets.VPS_SSH_KEY }}
