name: Deploy to VPS (Docker Compose)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t sintesi-app:latest .

      - name: Stop and remove old container (if exists)
        run: docker-compose down || true

      - name: Start new container with docker-compose
        run: docker-compose up -d --force-recreate
